ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  favicon: favicon.png
  title: "nbdev"
  description: "nbdev landing page"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: false
  repo-branch: master
  repo-url: https://github.com/seem/nbdev-web/
  repo-actions: [issue]
  site-url: https://seem.github.io/nbdev-web/
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/seem/nbdev-web/

metadata-files: 
  - custom.yml
